# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey
  namespace: argocd1
spec:
  replicas: {{ .Values.surveyDeployment.replicas }}
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
    spec:
      containers:
      - name: container-0
        image: {{ .Values.surveyDeployment.image }}
        ports:
        - containerPort: {{ .Values.surveyDeployment.containerPort }}
