apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '13'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.62.250"],"port":30892,"protocol":"TCP","serviceName":"hw2:springboot-hw3","allNodes":true},{"addresses":["172.31.62.250"],"port":80,"protocol":"HTTP","serviceName":"hw2:survey","ingressName":"hw2:ec2","hostname":"hw3swe645.net","path":"/","allNodes":false},{"addresses":["172.31.62.250"],"port":31339,"protocol":"TCP","serviceName":"hw2:survey-nodeport","allNodes":true}]
  creationTimestamp: '2023-10-07T16:55:08Z'
  generation: 20
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  name: survey
  namespace: argocd1
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
    spec:
      containers:
        - image: njogani/swe645_hw2:202311270456
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 8080
              name: survey
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
