apiVersion: v1
kind: Service
metadata:
  annotations:
  name: springboot-hw3
  namespace: argocd1
spec:
  clusterIP: 10.43.93.61
  clusterIPs:
    - 10.43.93.61
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30892
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  sessionAffinity: None
  type: NodePort
