# springboot-hw3-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-hw3
  namespace: argocd1
spec:
  type: {{ .Values.springbootHw3Service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.springbootHw3Service.port }}
      targetPort: {{ .Values.springbootHw3Service.port }}
      nodePort: {{ .Values.springbootHw3Service.nodePort }}
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
