# survey-clusterip-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: survey-clusterip
  namespace: argocd1
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  ports:
    - protocol: TCP
      port: {{ .Values.surveyService.port }}
      targetPort: {{ .Values.surveyService.port }}
  type: {{ .Values.surveyService.type }}
